version: '3.6'
services:
    storage:
        image: busybox
        volumes:
            - storage:/var/lib/mysql
    mysql:
        build:
            context: ./mysql/
            dockerfile: ./Dockerfile
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        volumes:
            - storage:/var/lib/mysql
        ports:
            - "3306:3306"
volumes:
    storage:
