spring:
  datasource:
    url: "jdbc:mysql://${DATASOURCE_DATABASE_URL:127.0.0.1:3306/iddd_chat_room_dev?characterEncoding=UTF8&connectionCollation=utf8mb4_bin&useSSL=false}"
    username: ${DATASOURCE_DATABASE_USERNAME:root}
    password: ${DATASOURCE_DATABASE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    # HikariDataSource is default type, but I'll write it down explicitly.
    type: com.zaxxer.hikari.HikariDataSource
    # HikariCP
    # @link https://github.com/brettwooldridge/HikariCP#frequently-used
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 5
      minimum-idle: 10
  flyway:
    user: ${DATASOURCE_DATABASE_MIGRATION_USERNAME:root}
    password: ${DATASOURCE_DATABASE_PASSWORD:}
